name = "CivCubed Pack"
author = "mazziechai"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c9607a738aed306734d916f9126b7fb10bc8c18f5800ff85331525bdb8408ca"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
