name = "CivCubed Pack"
author = "mazziechai"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b837e7f5ed408f232ad79b932821c06c9f95b5e88b38d891a2ccf19be2433e56"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
