name = "CivCubed Pack"
author = "mazziechai"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68eeff6a62a2e76414b31496cc74f95fe7b6cd4ee25a80407b5ff84669f3b47b"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
