name = "CivCubed Pack"
author = "mazziechai"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fade2e283f6bbf00acb506fd06e28e1d0300f27afb1a0cf7b752e1b563dcb14"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
