name = "CivCubed Pack"
author = "mazziechai"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de52f398910905d0d3c4184d79ac225c13a4e15be62cfcaddaae70506d470e22"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
