name = "CivCubed Pack"
author = "mazziechai"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "654692133a60c87054e82dd18a63a56e5d0ccb5379cc643b81605a3939d37a44"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
