name = "CivCubed Pack"
author = "mazziechai"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c6f39755775c56be224a6b6cbab0b9e325db916b4995178691131408b747da1"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
