name = "CivCubed Pack"
author = "mazziechai"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee86950082b2fead2c48bf8b8823fbe4bc19f2f72af2f39d5d847eaf90bd9882"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
