name = "CivCubed Pack"
author = "mazziechai"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2db11bfd724503af47a5e98f1940343f70d20654184fa58d698c9aad889b857"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
