name = "CivCubed Pack"
author = "mazziechai"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57544dbf8bf0165f85a456ffeb1cd54cf3d29eb23abb8c01a5ddd013c7c5f9e1"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
