name = "CivCubed Pack"
author = "mazziechai"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b698efc72bb7bdf14d4549d956dc3f4ee3806baef52d2461a38a6594d19fc092"

[versions]
minecraft = "1.20.1"
quilt = "0.21.2"
